use super::*;

impl Protocol {
    pub(super) fn start_next_slot(&mut self) {
        self.state.slot += 1;
        self.state.slot_started = Instant::now();
        self.state.current_result = None;
        self.state.mode = if self.total_eligible_tickets() == 0 {
            Mode::Pbm
        } else {
            Mode::Normal
        };
        (self.state.current_leader, self.state.current_ticket_id) = self.select_leader();
        self.state.exec_status = ExecStatus::Executing;
    }

    pub(super) fn finish_slot(&mut self) -> bool {
        if self
            .state
            .remote_slot_results
            .remove(&self.state.slot)
            .is_some()
        {
            // Older nodes could queue remote blocks. Never apply them without authenticated replay.
            self.state.events.push_front(format!(
                "rejected remote block for slot {}: remote block application is unsupported",
                self.state.slot
            ));
        }

        if self.canonical_parent_hash(self.state.slot).is_none() {
            self.state.events.push_front(format!(
                "slot {} deferred: canonical parent unavailable",
                self.state.slot
            ));
            return false;
        }
        if let Err(error) = self.prevalidate_active_linear_slot() {
            self.state
                .events
                .push_front(format!("slot {} rejected: {}", self.state.slot, error));
            return false;
        }

        let staged = self.stage_local_slot();
        let Ok((result, candidate_state, candidate_rng)) = staged else {
            let error = staged.err().unwrap_or("unknown staged execution error");
            self.state
                .events
                .push_front(format!("slot {} discarded: {}", self.state.slot, error));
            return false;
        };

        if let Err(error) = self.persist_candidate(&candidate_state) {
            // Candidate state, including mempool removals and block indexes, is never installed.
            self.state.events.push_front(format!(
                "slot {} discarded: candidate persistence failed ({})",
                self.state.slot, error
            ));
            return false;
        }

        // State installation is one assignment after execution, recording, and boundary updates succeed.
        self.state = candidate_state;
        self.rng = candidate_rng;
        self.p2p.broadcast_message(&encode_block(&result));
        true
    }

    fn stage_local_slot(&mut self) -> Result<(Block, ProtocolState, StdRng), &'static str> {
        let live_state = self.state.clone();
        let live_rng = self.rng.clone();
        self.state = live_state.clone();
        self.rng = live_rng.clone();

        let result = (|| {
            // Reject a stale or non-tip local slot before mutating the staged execution overlay.
            self.prevalidate_active_linear_slot()?;
            let no_tickets = self.total_eligible_tickets() == 0;
            let result = if no_tickets {
                self.protocol_no_tickets_block()
            } else if self.is_local_leader() {
                self.validator_block()
            } else {
                // A miss generated by a non-leader node is provisional and must not punish it.
                self.protocol_miss_block()
            };

            self.prevalidate_linear_tip(&result)?;
            #[cfg(test)]
            if self.test_fail_next_execution {
                self.test_fail_next_execution = false;
                return Err("injected staged execution failure");
            }
            self.record_linear_tip(result.clone())?;
            self.run_boundaries();
            Ok(result)
        })();

        let candidate_state = std::mem::replace(&mut self.state, live_state);
        let candidate_rng = std::mem::replace(&mut self.rng, live_rng);
        result.map(|block| (block, candidate_state, candidate_rng))
    }

    fn persist_candidate(&mut self, _candidate: &ProtocolState) -> Result<(), &'static str> {
        // There is no persistent database in this prototype. Keep this fallible boundary so a
        // storage backend can be added without weakening the all-or-nothing state transition.
        #[cfg(test)]
        if self.test_fail_next_persistence {
            self.test_fail_next_persistence = false;
            return Err("injected persistence failure");
        }
        Ok(())
    }

    fn prevalidate_linear_tip(&self, block: &Block) -> Result<(), &'static str> {
        // Round-trip through the actual V1 wire decoder before candidate recording or installation.
        let wire = block
            .wire_bytes()
            .ok_or("candidate has invalid canonical block encoding")?;
        let decoded = Block::from_wire_bytes(&wire)
            .ok_or("candidate failed claimed-hash or canonical decoding validation")?;
        if decoded != *block || !block.validate_commitments() {
            return Err("candidate failed block commitment validation");
        }

        self.prevalidate_active_linear_slot()?;
        if block.slot() != self.state.slot {
            return Err("candidate slot does not match the active local slot");
        }
        let expected_parent = if self.state.slot == 0 {
            ZERO_HASH
        } else {
            self.state
                .blocks
                .get(&self.state.slot.saturating_sub(1))
                .map(Block::hash)
                .ok_or("canonical tip block is unavailable")?
        };
        if block.header.parent_hash != expected_parent {
            return Err("candidate parent is not the canonical tip");
        }
        Ok(())
    }

    fn prevalidate_active_linear_slot(&self) -> Result<(), &'static str> {
        let expected_slot = self
            .state
            .blocks
            .keys()
            .max()
            .copied()
            .map(|slot| slot.saturating_add(1))
            .unwrap_or(0);
        if self.state.slot != expected_slot {
            return Err("active slot is not the next canonical slot");
        }
        if self.state.blocks.contains_key(&self.state.slot) {
            return Err("active slot already has a canonical block");
        }
        Ok(())
    }

    fn record_linear_tip(&mut self, result: Block) -> Result<(), &'static str> {
        self.prevalidate_linear_tip(&result)?;
        if self.state.current_result.is_some() {
            return Err("active slot already has a recorded result");
        }

        self.state.current_result = Some(result.clone());
        self.update_liveness(&result);
        self.state.blocks_this_sub_epoch.push(match result.kind() {
            BlockKind::Validator => result.proposer.clone(),
            _ => None,
        });
        if !self.record_block(&result) {
            return Err("candidate block persistence index rejected the canonical tip");
        }
        self.state.history.push_front(result);
        if self.state.history.len() > 50 {
            self.state.history.pop_back();
        }
        Ok(())
    }

    pub(super) fn is_local_leader(&self) -> bool {
        let Some(local_id) = &self.state.local_validator_id else {
            return false;
        };
        self.state.current_leader == *local_id
    }

    pub(super) fn total_eligible_tickets(&self) -> usize {
        self.state
            .tickets
            .iter()
            .filter(|t| !t.dead && !t.muted && self.validator_active(&t.owner))
            .count()
    }

    pub(super) fn validator_active(&self, id: &str) -> bool {
        self.state
            .validators
            .iter()
            .any(|v| v.id == id && v.state == ValidatorState::Active)
    }

    pub(super) fn leader_selection_block_hash(&self, slot_index: u64) -> Option<Hash> {
        historical_block_hash(&self.state.blocks, slot_index)
    }

    pub(super) fn select_leader(&self) -> (String, u64) {
        let eligible: Vec<&Ticket> = self
            .state
            .tickets
            .iter()
            .filter(|t| !t.dead && !t.muted && self.validator_active(&t.owner))
            .collect();
        let Some(historical_block_hash) = self.leader_selection_block_hash(self.state.slot) else {
            return ("protocol".to_string(), ZERO_TICKET_ID);
        };
        select_leader_ticket(historical_block_hash, self.state.slot, &eligible)
            .unwrap_or_else(|| ("protocol".to_string(), ZERO_TICKET_ID))
    }

    pub(super) fn validator_block(&mut self) -> Block {
        let mut gas = 0_u64;
        let mut fees = 0_u64;
        let mut transactions = Vec::new();
        while let Some(tx) = self.state.mempool.front().cloned() {
            if transactions.len() >= MAX_BLOCK_TRANSACTIONS {
                break;
            }
            if tx.chain_id != CHAIN_ID {
                self.state.mempool.pop_front();
                continue;
            }
            if tx.valid_after_slot > self.state.slot {
                break;
            }
            let Some(next_gas) = gas.checked_add(tx.gas).filter(|sum| *sum <= MAX_BLOCK_GAS) else {
                break;
            };
            let Some(next_fees) = fees.checked_add(tx.fee_quarks) else {
                break;
            };
            let fee = tx.fee_quarks as u128;
            let executed = match tx.kind {
                TxKind::RegisterValidator => {
                    // Registration data is encoded in tx.data because the Tx envelope is shared with transfers.
                    let Some((validator_pubkey, reward_address)) =
                        decode_register_validator_data(&tx.data)
                    else {
                        self.state.mempool.pop_front();
                        continue;
                    };
                    let Some(validator_pubkey) = self.normalize_validator_pubkey(&validator_pubkey)
                    else {
                        self.state.mempool.pop_front();
                        continue;
                    };
                    if self.state.validators.iter().any(|v| v.id == tx.to)
                        || self.validator_pubkey_registered(&validator_pubkey)
                        || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, fee)
                    {
                        self.state.mempool.pop_front();
                        continue;
                    }
                    self.state.mempool.pop_front();
                    if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                        false
                    } else {
                        self.register_validator_record(
                            tx.to.clone(),
                            &tx.from,
                            validator_pubkey,
                            reward_address,
                        );
                        true
                    }
                }
                TxKind::BuyTicket => {
                    // Tx.value carries the requested ticket count for fixed-fee validator system txs.
                    let Some(count) = u64::try_from(tx.value).ok().filter(|count| *count > 0)
                    else {
                        self.state.mempool.pop_front();
                        continue;
                    };
                    let cost = TICKET_COST_QUARKS.saturating_mul(tx.value);
                    let required = cost.saturating_add(fee);
                    if self.validator_owner_account(&tx.to).as_deref() != Some(tx.from.as_str())
                        || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, required)
                    {
                        self.state.mempool.pop_front();
                        continue;
                    }
                    self.state.mempool.pop_front();
                    if !self.debit_balance(&tx.from, TOKEN_ETX_ID, cost) {
                        false
                    } else if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                        self.credit_balance(&tx.from, TOKEN_ETX_ID, cost);
                        false
                    } else {
                        self.burn_and_mint_tickets(&tx.to, count);
                        self.refresh_validator_activation(&tx.to);
                        true
                    }
                }
                TxKind::WalletToVault => {
                    // Vault deposits spend account balance immediately and may activate an already-ticketed validator.
                    let required = tx.value.saturating_add(fee);
                    if self.validator_owner_account(&tx.to).as_deref() != Some(tx.from.as_str())
                        || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, required)
                        || !self.state.validators.iter().any(|v| v.id == tx.to)
                    {
                        self.state.mempool.pop_front();
                        continue;
                    }
                    self.state.mempool.pop_front();
                    if !self.debit_balance(&tx.from, TOKEN_ETX_ID, tx.value) {
                        false
                    } else if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                        self.credit_balance(&tx.from, TOKEN_ETX_ID, tx.value);
                        false
                    } else if let Some(v) = self.state.validators.iter_mut().find(|v| v.id == tx.to)
                    {
                        v.vault_quarks = v.vault_quarks.saturating_add(tx.value);
                        self.refresh_validator_activation(&tx.to);
                        true
                    } else {
                        self.credit_balance(&tx.from, TOKEN_ETX_ID, tx.value);
                        false
                    }
                }
                TxKind::VaultToWallet => {
                    // Withdrawals keep the fee in the owner account path but move value out of validator vault.
                    if self.validator_owner_account(&tx.to).as_deref() != Some(tx.from.as_str())
                        || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, fee)
                        || tx.value > self.validator_withdrawable_vault_quarks(&tx.to)
                    {
                        self.state.mempool.pop_front();
                        continue;
                    }
                    self.state.mempool.pop_front();
                    if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                        false
                    } else if let Some(v) = self.state.validators.iter_mut().find(|v| v.id == tx.to)
                    {
                        v.vault_quarks -= tx.value;
                        self.credit_balance(&tx.from, TOKEN_ETX_ID, tx.value);
                        self.refresh_validator_activation(&tx.to);
                        true
                    } else {
                        false
                    }
                }
                _ => {
                    let can_pay = if tx.token_id == tx.fee_token_id {
                        self.can_pay_fee(&tx.from, tx.token_id, tx.value.saturating_add(fee))
                    } else {
                        self.can_pay_value(&tx.from, tx.token_id, tx.value)
                            && self.can_pay_fee(&tx.from, tx.fee_token_id, fee)
                    };
                    if !can_pay {
                        self.state.mempool.pop_front();
                        continue;
                    }
                    self.state.mempool.pop_front();
                    if !self.debit_balance(&tx.from, tx.token_id, tx.value) {
                        false
                    } else {
                        self.credit_balance(&tx.to, tx.token_id, tx.value);
                        if !self.debit_balance(&tx.from, tx.fee_token_id, fee) {
                            self.debit_balance(&tx.to, tx.token_id, tx.value);
                            self.credit_balance(&tx.from, tx.token_id, tx.value);
                            false
                        } else {
                            true
                        }
                    }
                }
            };
            if !executed {
                continue;
            }
            gas = next_gas;
            fees = next_fees;
            transactions.push(tx);
            if self.rng.gen_bool(0.07) {
                break;
            }
        }
        let fees = fees as u128;
        // Fees are supply burns and also feed burn-offset; ticket burns are tracked elsewhere and excluded.
        self.state.fees_burned_total = self.state.fees_burned_total.saturating_add(fees);
        self.state.burn_this_sub_epoch = self.state.burn_this_sub_epoch.saturating_add(fees);
        self.state.sub_epoch_burned_quarks =
            self.state.sub_epoch_burned_quarks.saturating_add(fees);
        self.state.epoch_burned_quarks = self.state.epoch_burned_quarks.saturating_add(fees);
        let base_reward = self.base_reward_per_block_quarks();
        if let Some(v) = self
            .state
            .validators
            .iter_mut()
            .find(|v| v.id == self.state.current_leader)
        {
            // Base issuance is minted to validator vaults, so total supply changes at block production.
            v.blocks_this_sub_epoch += 1;
            if v.miss_counter > 0 {
                v.miss_counter -= 1;
            }
        }
        if self
            .state
            .validators
            .iter()
            .any(|v| v.id == self.state.current_leader)
        {
            let leader = self.state.current_leader.clone();
            self.lock_validator_reward(&leader, base_reward);
            self.state.base_issuance_total =
                self.state.base_issuance_total.saturating_add(base_reward);
            self.state.sub_epoch_issued_quarks = self
                .state
                .sub_epoch_issued_quarks
                .saturating_add(base_reward);
            self.state.epoch_issued_quarks =
                self.state.epoch_issued_quarks.saturating_add(base_reward);
        }

        self.build_block(
            BlockKind::Validator,
            Some(self.state.current_leader.clone()),
            self.state.current_ticket_id,
            transactions,
            gas,
            ProtocolData {
                missed_proposer: None,
                fees_burned: fees as u64,
            },
        )
        .expect("validator block has a canonical parent and valid commitments")
    }

    pub(super) fn protocol_miss_block(&mut self) -> Block {
        if self.state.local_validator_id.as_deref() != Some(self.state.current_leader.as_str()) {
            // Standard nodes cannot know whether a remote leader was truly absent; avoid provisional penalties.
            return self
                .build_block(
                    BlockKind::ProtocolMiss,
                    None,
                    ZERO_TICKET_ID,
                    Vec::new(),
                    0,
                    ProtocolData {
                        missed_proposer: Some(self.state.current_leader.clone()),
                        fees_burned: 0,
                    },
                )
                .expect("miss block has a canonical parent and valid commitments");
        }
        if let Some(v) = self
            .state
            .validators
            .iter_mut()
            .find(|v| v.id == self.state.current_leader)
        {
            v.miss_counter += 1;
            if v.miss_counter >= 10 {
                v.state = ValidatorState::PunishedCooldown;
                v.cooldown_until_epoch = Some(self.state.epoch_index + 1);
            }
        }
        self.build_block(
            BlockKind::ProtocolMiss,
            None,
            ZERO_TICKET_ID,
            Vec::new(),
            0,
            ProtocolData {
                missed_proposer: Some(self.state.current_leader.clone()),
                fees_burned: 0,
            },
        )
        .expect("miss block has a canonical parent and valid commitments")
    }

    pub(super) fn protocol_collision_block(&mut self) -> Block {
        self.build_block(
            BlockKind::ProtocolCollision,
            None,
            ZERO_TICKET_ID,
            Vec::new(),
            0,
            ProtocolData::empty(),
        )
        .expect("collision block has a canonical parent and valid commitments")
    }

    pub(super) fn protocol_no_tickets_block(&mut self) -> Block {
        let mut gas_used = 0_u64;
        let mut fees_burned = 0_u64;
        let mut transactions = Vec::new();

        if let Some(index) = self.select_pbm_tx_index()
            && let Some(tx) = self.state.pbm_pool.remove(index)
            && let Some((gas, fees)) = self.execute_pbm_tx(tx.clone())
        {
            // PBM advances the chain without tickets but only includes one deterministic bootstrap tx per slot.
            gas_used = gas;
            fees_burned = fees;
            transactions.push(tx);
            let fees = fees as u128;
            self.state.fees_burned_total = self.state.fees_burned_total.saturating_add(fees);
            self.state.burn_this_sub_epoch = self.state.burn_this_sub_epoch.saturating_add(fees);
            self.state.sub_epoch_burned_quarks =
                self.state.sub_epoch_burned_quarks.saturating_add(fees);
            self.state.epoch_burned_quarks = self.state.epoch_burned_quarks.saturating_add(fees);
        }

        self.deactivate_pbm_if_ready();

        self.build_block(
            BlockKind::ProtocolNoTickets,
            None,
            ZERO_TICKET_ID,
            transactions,
            gas_used,
            ProtocolData {
                missed_proposer: None,
                fees_burned,
            },
        )
        .expect("no-ticket block has a canonical parent and valid commitments")
    }

    pub(super) fn select_pbm_tx_index(&self) -> Option<usize> {
        let mut candidates: Vec<(usize, u64, Hash)> = self
            .state
            .pbm_pool
            .iter()
            .enumerate()
            .filter(|(_, tx)| {
                Protocol::pbm_allowed_kind(tx.kind) && tx.valid_after_slot <= self.state.slot
            })
            .filter_map(|(index, tx)| Some((index, tx.valid_after_slot, tx.hash()?)))
            .collect();
        candidates.sort_by(|a, b| (a.1, &a.2).cmp(&(b.1, &b.2)));
        candidates.first().map(|(index, _, _)| *index)
    }

    pub(super) fn execute_pbm_tx(&mut self, tx: Tx) -> Option<(u64, u64)> {
        let fee = tx.fee_quarks as u128;
        match tx.kind {
            TxKind::RegisterValidator => {
                let (validator_pubkey, reward_address) = decode_register_validator_data(&tx.data)?;
                let validator_pubkey = self.normalize_validator_pubkey(&validator_pubkey)?;
                if self.state.validators.iter().any(|v| v.id == tx.to)
                    || self.validator_pubkey_registered(&validator_pubkey)
                    || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, fee)
                {
                    return None;
                }
                if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                    return None;
                }
                self.register_validator_record(tx.to, &tx.from, validator_pubkey, reward_address);
                Some((tx.gas, tx.fee_quarks))
            }
            TxKind::WalletToVault => {
                let required = tx.value.saturating_add(fee);
                if self.validator_owner_account(&tx.to).as_deref() != Some(tx.from.as_str())
                    || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, required)
                    || !self.state.validators.iter().any(|v| v.id == tx.to)
                {
                    return None;
                }
                if !self.debit_balance(&tx.from, TOKEN_ETX_ID, tx.value) {
                    return None;
                }
                if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                    self.credit_balance(&tx.from, TOKEN_ETX_ID, tx.value);
                    return None;
                }
                if let Some(v) = self.state.validators.iter_mut().find(|v| v.id == tx.to) {
                    v.vault_quarks = v.vault_quarks.saturating_add(tx.value);
                    self.refresh_validator_activation(&tx.to);
                    return Some((tx.gas, tx.fee_quarks));
                }
                self.credit_balance(&tx.from, TOKEN_ETX_ID, tx.value);
                None
            }
            TxKind::BuyTicket => {
                let count = u64::try_from(tx.value).ok().filter(|count| *count > 0)?;
                let cost = TICKET_COST_QUARKS.saturating_mul(tx.value);
                let required = cost.saturating_add(fee);
                if self.validator_owner_account(&tx.to).as_deref() != Some(tx.from.as_str())
                    || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, required)
                {
                    return None;
                }
                if !self.debit_balance(&tx.from, TOKEN_ETX_ID, cost) {
                    return None;
                }
                if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                    self.credit_balance(&tx.from, TOKEN_ETX_ID, cost);
                    return None;
                }
                self.burn_and_mint_tickets(&tx.to, count);
                self.refresh_validator_activation(&tx.to);
                Some((tx.gas, tx.fee_quarks))
            }
            _ => None,
        }
    }

    pub(super) fn deactivate_pbm_if_ready(&mut self) {
        if self.total_eligible_tickets() == 0 {
            return;
        }
        self.state.mode = Mode::Normal;
        while let Some(tx) = self.state.pbm_pool.pop_front() {
            self.state.mempool.push_back(tx);
        }
        self.state
            .events
            .push_front("PBM deactivated: eligible ticket available".to_string());
    }

    pub(super) fn run_boundaries(&mut self) {
        if self.state.slot > 0 && self.state.slot.is_multiple_of(SUB_EPOCH_SLOTS) {
            let produced = self
                .state
                .blocks_this_sub_epoch
                .iter()
                .filter(|p| p.is_some())
                .count() as u64;
            if produced > 0 {
                let k = self.state.burn_offset_k_permille as u128;
                let opb = k * self.state.burn_this_sub_epoch / 1000 / produced as u128;
                let proposers: Vec<String> = self
                    .state
                    .blocks_this_sub_epoch
                    .iter()
                    .flatten()
                    .cloned()
                    .collect();
                for pid in proposers {
                    if self.state.validators.iter().any(|v| v.id == pid) {
                        // Burn-offset is minted at sub-epoch close from fee burns only, not ticket burns.
                        self.lock_validator_reward(&pid, opb);
                        self.state.burn_offset_total += opb;
                        self.state.epoch_issued_quarks =
                            self.state.epoch_issued_quarks.saturating_add(opb);
                    }
                }
            }
            for v in &mut self.state.validators {
                v.blocks_this_sub_epoch = 0;
            }
            self.state.burn_this_sub_epoch = 0;
            self.state.sub_epoch_issued_quarks = 0;
            self.state.sub_epoch_burned_quarks = 0;
            self.state.blocks_this_sub_epoch.clear();
            self.state.sub_epoch_index += 1;
            self.state.events.push_front(format!(
                "sub-epoch transition {}",
                self.state.sub_epoch_index
            ));
        }
        if self.state.slot > 0
            && self
                .state
                .slot
                .is_multiple_of(SUB_EPOCH_SLOTS * EPOCH_SUB_EPOCHS)
        {
            let next_epoch = self.state.epoch_index + 1;
            if next_epoch.is_multiple_of(EPOCHS_PER_YEAR) {
                // Inflation decay updates the fixed block reward for the next annual period.
                self.state.annual_inflation_ppb =
                    (self.state.annual_inflation_ppb * 9 / 10).max(5_000_000);
                self.recompute_base_reward_per_block();
            }
            self.state.epoch_index = next_epoch;
            self.unlock_rewards_for_epoch(next_epoch);
            self.state.epoch_issued_quarks = 0;
            self.state.epoch_burned_quarks = 0;
            self.finalize_retire_for_epoch(self.state.epoch_index);
            self.rotate_epoch_seed();
            self.process_epoch_validator_transitions();
            self.state
                .events
                .push_front(format!("epoch transition {}", self.state.epoch_index));
        }
    }

    pub(super) fn canonical_parent_hash(&self, slot: u64) -> Option<Hash> {
        if slot == 0 {
            return Some(ZERO_HASH);
        }
        self.state
            .blocks
            .get(&slot.saturating_sub(1))
            .map(Block::hash)
    }

    pub(super) fn build_block(
        &self,
        block_kind: BlockKind,
        proposer: Option<String>,
        ticket_id: u64,
        transactions: Vec<Tx>,
        gas_used: u64,
        protocol_data: ProtocolData,
    ) -> Option<Block> {
        Block::new(
            self.state.slot,
            block_kind,
            self.canonical_parent_hash(self.state.slot)?,
            proposer,
            ticket_id,
            transactions,
            gas_used,
            protocol_data,
        )
    }

    pub(super) fn record_slot(&mut self, result: Block) -> bool {
        if !self.validate_block_commitments_and_parent(&result) {
            self.state.events.push_front(format!(
                "rejected block {}: invalid commitment or parent",
                short_hash(&result.hash())
            ));
            return false;
        }
        self.state.current_result = Some(result.clone());
        // Recent provisional miss/no-ticket entries can be replaced by late validator blocks from peers.
        let replaced = self
            .state
            .history
            .iter()
            .find(|h| h.slot() == result.slot())
            .cloned();
        let replacing = replaced.is_some();
        self.state.history.retain(|h| h.slot() != result.slot());
        if let Some(old) = &replaced {
            self.revert_replaced_result(old, &result);
        }
        self.update_liveness(&result);
        self.state.blocks_this_sub_epoch.push(match result.kind() {
            BlockKind::Validator => result.proposer.clone(),
            _ => None,
        });
        if !self.record_block(&result) {
            return false;
        }
        self.state.history.push_front(result);
        if self.state.history.len() > 50 {
            self.state.history.pop_back();
        }
        if replacing {
            self.rebuild_liveness_from_history();
        }
        true
    }

    pub(super) fn merge_slot_result(&mut self, result: Block) {
        // Peer history is correction-only after bootstrap: validator blocks can replace weaker local results.
        let existing = self
            .state
            .history
            .iter()
            .find(|h| h.slot() == result.slot())
            .cloned();
        let should_apply = match existing.as_ref() {
            Some(old) if old.kind() == BlockKind::Validator => false,
            Some(old)
                if result.kind() == BlockKind::Validator && old.kind() != BlockKind::Validator =>
            {
                true
            }
            None => true,
            _ => false,
        };
        if !should_apply {
            return;
        }
        if self.state.blocks.keys().any(|slot| *slot > result.slot()) {
            // Replacing an ancestor would invalidate every descendant parent hash.
            return;
        }
        if !self.validate_block_commitments_and_parent(&result) {
            return;
        }

        self.state.history.retain(|h| h.slot() != result.slot());
        if let Some(old) = &existing {
            self.revert_replaced_result(old, &result);
        }
        if !self.record_block(&result) {
            return;
        }
        self.state.history.push_front(result.clone());

        let mut entries: Vec<Block> = self.state.history.iter().cloned().collect();
        entries.sort_by_key(|e| std::cmp::Reverse(e.slot()));
        entries.truncate(50);
        self.state.history = std::collections::VecDeque::from(entries);
        self.rebuild_liveness_from_history();
        self.state.events.push_front(format!(
            "slot {} corrected from peer: {:?}",
            result.slot(),
            result.kind()
        ));
    }

    pub(super) fn revert_replaced_result(&mut self, old: &Block, new: &Block) {
        // Undo local provisional punishment if a valid validator block later replaces the miss.
        if old.kind() != BlockKind::ProtocolMiss
            || new.kind() != BlockKind::Validator
            || old.leader() != new.leader()
        {
            return;
        }
        let mut refresh_id = None;
        if let Some(v) = self
            .state
            .validators
            .iter_mut()
            .find(|v| v.id == old.leader())
        {
            if v.miss_counter > 0 {
                v.miss_counter -= 1;
            }
            if v.state == ValidatorState::PunishedCooldown && v.miss_counter < 10 {
                v.cooldown_until_epoch = None;
                v.state = ValidatorState::Inactive;
                refresh_id = Some(v.id.clone());
            }
        }
        if let Some(id) = refresh_id {
            self.refresh_validator_activation(&id);
        }
    }

    pub(super) fn validate_block_commitments_and_parent(&self, block: &Block) -> bool {
        block.validate_commitments()
            && self
                .canonical_parent_hash(block.slot())
                .is_some_and(|parent| block.validate_parent(parent))
    }

    pub(super) fn record_block(&mut self, block: &Block) -> bool {
        if !self.validate_block_commitments_and_parent(block) {
            return false;
        }
        let number = block.slot();
        if let Some(old) = self.state.blocks.get(&number) {
            self.state.block_hash_to_number.remove(&old.hash());
        }
        let hash = block.hash();
        self.state.block_hash_to_number.insert(hash, number);
        self.state.blocks.insert(number, block.clone());

        if let Some(transaction_hashes) = block.transaction_hashes() {
            for (index, transaction_hash) in transaction_hashes.into_iter().enumerate() {
                if let Some(record) = self.state.raw_txs.get_mut(&transaction_hash) {
                    record.block_number = Some(number);
                    record.block_hash = Some(hash);
                    record.tx_index = u64::try_from(index).ok();
                    record.success = Some(true);
                }
            }
        }
        true
    }

    pub(super) fn update_liveness(&mut self, result: &Block) {
        let epoch = result.slot() / (SUB_EPOCH_SLOTS * EPOCH_SUB_EPOCHS);
        if epoch != self.state.liveness_epoch {
            self.state.liveness_epoch = epoch;
            self.state.liveness_counted_slots.clear();
            self.state.liveness_total_slots = 0;
            self.state.liveness_validator_slots = 0;
        }
        if !self.state.liveness_counted_slots.insert(result.slot()) {
            return;
        }
        self.state.liveness_total_slots += 1;
        if result.kind() == BlockKind::Validator {
            self.state.liveness_validator_slots += 1;
        }
        self.state.epoch_total_slots = self.state.liveness_total_slots;
        self.state.epoch_validator_blocks = self.state.liveness_validator_slots;
    }

    pub(super) fn rebuild_liveness_from_history(&mut self) {
        self.state.liveness_counted_slots.clear();
        self.state.liveness_total_slots = 0;
        self.state.liveness_validator_slots = 0;

        let mut entries: Vec<Block> = self.state.history.iter().cloned().collect();
        entries.sort_by_key(Block::slot);
        if let Some(last) = entries.last() {
            self.state.liveness_epoch = last.slot() / (SUB_EPOCH_SLOTS * EPOCH_SUB_EPOCHS);
        }
        for e in &entries {
            let epoch = e.slot() / (SUB_EPOCH_SLOTS * EPOCH_SUB_EPOCHS);
            if epoch != self.state.liveness_epoch {
                continue;
            }
            if self.state.liveness_counted_slots.insert(e.slot()) {
                self.state.liveness_total_slots += 1;
                if e.kind() == BlockKind::Validator {
                    self.state.liveness_validator_slots += 1;
                }
            }
        }
        self.state.epoch_total_slots = self.state.liveness_total_slots;
        self.state.epoch_validator_blocks = self.state.liveness_validator_slots;
    }

    pub(super) fn rotate_epoch_seed(&mut self) {
        let mut data = Vec::new();
        data.extend_from_slice(&self.state.epoch_seed);
        data.extend_from_slice(&self.state.epoch_index.to_be_bytes());
        self.state.epoch_seed = hash_with_domain(EPOCH_SEED_DOMAIN, &data);
    }

    pub(super) fn process_epoch_validator_transitions(&mut self) {
        let mut refresh_ids = Vec::new();
        let vault_minimums: HashMap<String, u128> = self
            .state
            .validators
            .iter()
            .map(|v| (v.id.clone(), self.validator_vault_minimum_quarks(&v.id)))
            .collect();
        for v in &mut self.state.validators {
            if v.state == ValidatorState::Jailed {
                continue;
            }
            if v.state == ValidatorState::PunishedCooldown
                && let Some(until) = v.cooldown_until_epoch
                && self.state.epoch_index >= until
            {
                v.cooldown_until_epoch = None;
                let vault_minimum = vault_minimums.get(&v.id).copied().unwrap_or(0);
                if v.vault_quarks >= vault_minimum {
                    v.state = ValidatorState::Inactive;
                    refresh_ids.push(v.id.clone());
                } else {
                    v.state = ValidatorState::PausedLowVault;
                }
            }
        }
        for id in refresh_ids {
            self.refresh_validator_activation(&id);
        }
    }

    pub(super) fn finalize_retire_for_epoch(&mut self, epoch: u64) {
        let Some(ticket_ids) = self.state.retire_finalize.remove(&epoch) else {
            return;
        };
        let mut owners = Vec::new();
        for tid in ticket_ids {
            if let Some(t) = self.state.tickets.iter_mut().find(|t| t.id == tid) {
                owners.push(t.owner.clone());
                t.dead = true;
                t.muted = false;
                t.retiring = false;
                t.bucket = 0;
            }
        }
        owners.sort_unstable();
        owners.dedup();
        for owner in owners {
            self.refresh_validator_activation(&owner);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn protocol() -> Protocol {
        Protocol::new(Config {
            mode: NodeMode::Standard,
            p2p_port: 0,
            peers: Vec::new(),
            rpc_port: 0,
            validator_id: None,
            validator_account: None,
            genesis_path: "/definitely/missing/eternix-test-genesis.json".to_string(),
            no_tui: true,
        })
        .unwrap()
    }

    fn assert_canonical_state_unchanged(before: &ProtocolState, after: &ProtocolState) {
        // Events are local diagnostics, not canonical protocol state, and failures append one.
        let mut before = before.clone();
        let mut after = after.clone();
        before.events.clear();
        after.events.clear();
        assert_eq!(before, after);
    }

    #[test]
    fn empty_local_block_is_staged_and_installed_as_the_canonical_tip() {
        let mut protocol = protocol();

        assert!(protocol.finish_slot());

        let block = protocol
            .state
            .blocks
            .get(&0)
            .expect("slot zero block recorded");
        assert_eq!(block.kind(), BlockKind::ProtocolNoTickets);
        assert!(block.transactions.is_empty());
        assert_eq!(block.header.parent_hash, ZERO_HASH);
        assert_eq!(protocol.state.current_result.as_ref(), Some(block));
    }

    #[test]
    fn duplicate_and_non_tip_candidates_are_rejected_without_state_mutation() {
        let mut protocol = protocol();
        assert!(protocol.finish_slot());
        let duplicate = protocol.state.blocks.get(&0).cloned().unwrap();
        let before = protocol.state.clone();

        assert_eq!(
            protocol.record_linear_tip(duplicate),
            Err("active slot is not the next canonical slot")
        );
        assert_canonical_state_unchanged(&before, &protocol.state);

        protocol.start_next_slot();
        let before = protocol.state.clone();
        let non_tip = Block::new(
            1,
            BlockKind::ProtocolNoTickets,
            ZERO_HASH,
            None,
            ZERO_TICKET_ID,
            Vec::new(),
            0,
            ProtocolData::empty(),
        )
        .unwrap();

        assert_eq!(
            protocol.record_linear_tip(non_tip),
            Err("candidate parent is not the canonical tip")
        );
        assert_canonical_state_unchanged(&before, &protocol.state);
    }

    #[test]
    fn injected_execution_failure_discards_the_entire_candidate() {
        let mut protocol = protocol();
        let before = protocol.state.clone();
        protocol.test_fail_next_execution = true;

        assert!(!protocol.finish_slot());

        assert_canonical_state_unchanged(&before, &protocol.state);
        assert!(
            protocol
                .state
                .events
                .front()
                .is_some_and(|event| event.contains("injected staged execution failure"))
        );
    }

    #[test]
    fn injected_persistence_failure_discards_the_entire_candidate() {
        let mut protocol = protocol();
        let before = protocol.state.clone();
        protocol.test_fail_next_persistence = true;

        assert!(!protocol.finish_slot());

        assert_canonical_state_unchanged(&before, &protocol.state);
        assert!(
            protocol
                .state
                .events
                .front()
                .is_some_and(|event| event.contains("candidate persistence failed"))
        );
    }

    #[test]
    fn included_pbm_transaction_leaves_the_pool_only_after_commit() {
        let mut protocol = protocol();
        let sender = "0x1111111111111111111111111111111111111111";
        protocol.credit_balance(sender, TOKEN_ETX_ID, 10_000);
        let validator_key = SigningKey::random(&mut OsRng);
        let validator_pubkey = format!(
            "0x{}",
            hex::encode(
                validator_key
                    .verifying_key()
                    .to_encoded_point(false)
                    .as_bytes()
            )
        );
        let transaction = Tx {
            chain_id: CHAIN_ID,
            from: sender.to_string(),
            nonce: 0,
            to: "val-0001".to_string(),
            token_id: TOKEN_ETX_ID,
            value: 0,
            gas: 1000,
            fee_quarks: 10_000,
            max_fee_per_gas: 10,
            kind: TxKind::RegisterValidator,
            valid_after_slot: 0,
            fee_token_id: TOKEN_ETX_ID,
            data: encode_register_validator_data(&validator_pubkey, sender),
            signature_hex: String::new(),
        };
        protocol.state.pbm_pool.push_back(transaction.clone());
        let before = protocol.state.clone();
        protocol.test_fail_next_persistence = true;

        assert!(!protocol.finish_slot());
        assert_canonical_state_unchanged(&before, &protocol.state);
        assert_eq!(protocol.state.pbm_pool.front(), Some(&transaction));

        assert!(protocol.finish_slot());
        assert!(protocol.state.pbm_pool.is_empty());
        assert_eq!(
            protocol
                .state
                .blocks
                .get(&0)
                .map(|block| &block.transactions),
            Some(&vec![transaction])
        );
    }

    #[test]
    fn block_storage_rejects_parent_mismatch() {
        let mut protocol = protocol();
        let parent = protocol
            .build_block(
                BlockKind::ProtocolNoTickets,
                None,
                ZERO_TICKET_ID,
                Vec::new(),
                0,
                ProtocolData::empty(),
            )
            .unwrap();
        assert!(protocol.record_block(&parent));

        protocol.state.slot = 1;
        let child = protocol
            .build_block(
                BlockKind::ProtocolNoTickets,
                None,
                ZERO_TICKET_ID,
                Vec::new(),
                0,
                ProtocolData::empty(),
            )
            .unwrap();
        assert_eq!(child.header.parent_hash, parent.hash());

        let mut mismatched = child.clone();
        mismatched.header.parent_hash = [0xff; 32];
        assert!(!protocol.record_block(&mismatched));
        assert!(protocol.record_block(&child));
    }

    #[test]
    fn canonical_block_transaction_is_queryable_by_hash() {
        let mut protocol = protocol();
        let transaction = Tx {
            chain_id: CHAIN_ID,
            from: "0x1111111111111111111111111111111111111111".to_string(),
            nonce: 0,
            to: "0x2222222222222222222222222222222222222222".to_string(),
            token_id: 0,
            value: 1,
            gas: 1000,
            fee_quarks: 10,
            max_fee_per_gas: 1,
            kind: TxKind::Transfer,
            valid_after_slot: 0,
            fee_token_id: 0,
            data: String::new(),
            signature_hex: String::new(),
        };
        let transaction_hash = transaction.hash().unwrap();
        let block = Block::new(
            0,
            BlockKind::Validator,
            ZERO_HASH,
            Some("val-test".to_string()),
            1,
            vec![transaction],
            1000,
            ProtocolData {
                missed_proposer: None,
                fees_burned: 10,
            },
        )
        .unwrap();
        assert!(protocol.record_block(&block));

        let response = protocol.handle_jsonrpc(
            json!(1),
            "eth_getTransactionByHash",
            &json!([format_hash(&transaction_hash)]),
        );
        assert_eq!(
            response["result"]["hash"],
            json!(format_hash(&transaction_hash))
        );
    }
}
