use super::*;

impl Protocol {
    pub(super) fn start_next_slot(&mut self) {
        self.state.slot += 1;
        self.state.slot_started = Instant::now();
        self.state.current_result = None;
        self.state.mode = if self.total_eligible_tickets() == 0 {
            Mode::Pbm
        } else {
            Mode::Normal
        };
        self.state.current_leader = self.select_leader();
        self.state.exec_status = ExecStatus::Executing;
    }

    pub(super) fn finish_slot(&mut self) {
        if let Some(remote) = self.state.remote_slot_results.remove(&self.state.slot) {
            // Future results are revalidated at slot close because ticket state can change while queued.
            if self.accept_remote_slot_result(&remote) {
                self.record_hash(&remote);
                self.record_slot(remote);
                self.run_boundaries();
                return;
            }
        }

        let no_tickets = self.total_eligible_tickets() == 0;
        let result = if no_tickets {
            self.protocol_no_tickets_block()
        } else if self.is_local_leader() {
            self.validator_block()
        } else {
            // A miss generated by a non-leader node is provisional and should not punish the remote validator.
            self.protocol_miss_block()
        };

        self.p2p.broadcast_message(&encode_slot_result(&result));
        self.record_hash(&result);
        self.record_slot(result);
        self.run_boundaries();
    }

    pub(super) fn is_local_leader(&self) -> bool {
        let Some(local_id) = &self.state.local_validator_id else {
            return false;
        };
        self.state.current_leader == *local_id
    }

    pub(super) fn total_eligible_tickets(&self) -> usize {
        self.state
            .tickets
            .iter()
            .filter(|t| !t.dead && !t.muted && self.validator_active(&t.owner))
            .count()
    }

    pub(super) fn validator_active(&self, id: &str) -> bool {
        self.state
            .validators
            .iter()
            .any(|v| v.id == id && v.state == ValidatorState::Active)
    }

    pub(super) fn leader_selection_block_hash(&self, slot_index: u64) -> Option<[u8; 32]> {
        if slot_index < crate::leader_selection::BLOCK_HASH_LOOKBACK_SLOTS {
            return Some(block_hash_bytes(0));
        }
        let block_number = historical_block_slot(slot_index);
        self.state
            .blocks
            .get(&block_number)
            .and_then(|block| decode_block_hash(&block.hash))
    }

    pub(super) fn select_leader(&mut self) -> String {
        let eligible: Vec<&Ticket> = self
            .state
            .tickets
            .iter()
            .filter(|t| !t.dead && !t.muted && self.validator_active(&t.owner))
            .collect();
        let Some(historical_block_hash) = self.leader_selection_block_hash(self.state.slot) else {
            return "protocol".to_string();
        };
        select_leader_owner(historical_block_hash, self.state.slot, &eligible)
            .unwrap_or_else(|| "protocol".to_string())
    }

    pub(super) fn validator_block(&mut self) -> SlotResult {
        let mut gas = 0_u64;
        let mut tx_count = 0_u32;
        let mut fees = 0_u64;
        while let Some(tx) = self.state.mempool.front() {
            if tx_count >= 3000 || gas + tx.gas > 16_000_000 {
                break;
            }
            let tx = tx.clone();
            let fee = tx.fee_quarks as u128;
            let executed = match tx.kind {
                "registerValidator" => {
                    // Registration data is encoded in tx.data because the Tx envelope is shared with transfers.
                    let Some((validator_pubkey, reward_address)) =
                        decode_register_validator_data(&tx.data)
                    else {
                        self.state.mempool.pop_front();
                        continue;
                    };
                    let Some(validator_pubkey) = self.normalize_validator_pubkey(&validator_pubkey)
                    else {
                        self.state.mempool.pop_front();
                        continue;
                    };
                    if self.state.validators.iter().any(|v| v.id == tx.to)
                        || self.validator_pubkey_registered(&validator_pubkey)
                        || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, fee)
                    {
                        self.state.mempool.pop_front();
                        continue;
                    }
                    self.state.mempool.pop_front();
                    if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                        false
                    } else {
                        self.register_validator_record(
                            tx.to.clone(),
                            &tx.from,
                            validator_pubkey,
                            reward_address,
                        );
                        true
                    }
                }
                "buyTicket" => {
                    // Tx.value carries the requested ticket count for fixed-fee validator system txs.
                    let Some(count) = u64::try_from(tx.value).ok().filter(|count| *count > 0)
                    else {
                        self.state.mempool.pop_front();
                        continue;
                    };
                    let cost = TICKET_COST_QUARKS.saturating_mul(tx.value);
                    let required = cost.saturating_add(fee);
                    if self.validator_owner_account(&tx.to).as_deref() != Some(tx.from.as_str())
                        || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, required)
                    {
                        self.state.mempool.pop_front();
                        continue;
                    }
                    self.state.mempool.pop_front();
                    if !self.debit_balance(&tx.from, TOKEN_ETX_ID, cost) {
                        false
                    } else if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                        self.credit_balance(&tx.from, TOKEN_ETX_ID, cost);
                        false
                    } else {
                        self.burn_and_mint_tickets(&tx.to, count);
                        self.refresh_validator_activation(&tx.to);
                        true
                    }
                }
                "walletToVault" => {
                    // Vault deposits spend account balance immediately and may activate an already-ticketed validator.
                    let required = tx.value.saturating_add(fee);
                    if self.validator_owner_account(&tx.to).as_deref() != Some(tx.from.as_str())
                        || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, required)
                        || !self.state.validators.iter().any(|v| v.id == tx.to)
                    {
                        self.state.mempool.pop_front();
                        continue;
                    }
                    self.state.mempool.pop_front();
                    if !self.debit_balance(&tx.from, TOKEN_ETX_ID, tx.value) {
                        false
                    } else if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                        self.credit_balance(&tx.from, TOKEN_ETX_ID, tx.value);
                        false
                    } else if let Some(v) = self.state.validators.iter_mut().find(|v| v.id == tx.to)
                    {
                        v.vault_quarks = v.vault_quarks.saturating_add(tx.value);
                        self.refresh_validator_activation(&tx.to);
                        true
                    } else {
                        self.credit_balance(&tx.from, TOKEN_ETX_ID, tx.value);
                        false
                    }
                }
                "vaultToWallet" => {
                    // Withdrawals keep the fee in the owner account path but move value out of validator vault.
                    if self.validator_owner_account(&tx.to).as_deref() != Some(tx.from.as_str())
                        || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, fee)
                        || tx.value > self.validator_withdrawable_vault_quarks(&tx.to)
                    {
                        self.state.mempool.pop_front();
                        continue;
                    }
                    self.state.mempool.pop_front();
                    if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                        false
                    } else if let Some(v) = self.state.validators.iter_mut().find(|v| v.id == tx.to)
                    {
                        v.vault_quarks -= tx.value;
                        self.credit_balance(&tx.from, TOKEN_ETX_ID, tx.value);
                        self.refresh_validator_activation(&tx.to);
                        true
                    } else {
                        false
                    }
                }
                _ => {
                    let can_pay = if tx.token_id == tx.fee_token_id {
                        self.can_pay_fee(&tx.from, tx.token_id, tx.value.saturating_add(fee))
                    } else {
                        self.can_pay_value(&tx.from, tx.token_id, tx.value)
                            && self.can_pay_fee(&tx.from, tx.fee_token_id, fee)
                    };
                    if !can_pay {
                        self.state.mempool.pop_front();
                        continue;
                    }
                    self.state.mempool.pop_front();
                    if !self.debit_balance(&tx.from, tx.token_id, tx.value) {
                        false
                    } else {
                        self.credit_balance(&tx.to, tx.token_id, tx.value);
                        if !self.debit_balance(&tx.from, tx.fee_token_id, fee) {
                            self.debit_balance(&tx.to, tx.token_id, tx.value);
                            self.credit_balance(&tx.from, tx.token_id, tx.value);
                            false
                        } else {
                            true
                        }
                    }
                }
            };
            if !executed {
                continue;
            }
            gas += tx.gas;
            fees += tx.fee_quarks;
            tx_count += 1;
            if self.rng.gen_bool(0.07) {
                break;
            }
        }
        let fees = fees as u128;
        // Fees are supply burns and also feed burn-offset; ticket burns are tracked elsewhere and excluded.
        self.state.fees_burned_total = self.state.fees_burned_total.saturating_add(fees);
        self.state.burn_this_sub_epoch = self.state.burn_this_sub_epoch.saturating_add(fees);
        self.state.sub_epoch_burned_quarks =
            self.state.sub_epoch_burned_quarks.saturating_add(fees);
        self.state.epoch_burned_quarks = self.state.epoch_burned_quarks.saturating_add(fees);
        let base_reward = self.base_reward_per_block_quarks();
        if let Some(v) = self
            .state
            .validators
            .iter_mut()
            .find(|v| v.id == self.state.current_leader)
        {
            // Base issuance is minted to validator vaults, so total supply changes at block production.
            v.blocks_this_sub_epoch += 1;
            if v.miss_counter > 0 {
                v.miss_counter -= 1;
            }
        }
        if self
            .state
            .validators
            .iter()
            .any(|v| v.id == self.state.current_leader)
        {
            let leader = self.state.current_leader.clone();
            self.lock_validator_reward(&leader, base_reward);
            self.state.base_issuance_total =
                self.state.base_issuance_total.saturating_add(base_reward);
            self.state.sub_epoch_issued_quarks = self
                .state
                .sub_epoch_issued_quarks
                .saturating_add(base_reward);
            self.state.epoch_issued_quarks =
                self.state.epoch_issued_quarks.saturating_add(base_reward);
        }

        if let Some(hash) = self.state.raw_tx_pending.pop_front()
            && let Some(rec) = self.state.raw_txs.get_mut(&hash)
        {
            rec.block_number = Some(self.state.slot);
            rec.block_hash = Some(format!(
                "0x{}",
                hex::encode(block_hash_bytes(self.state.slot))
            ));
            rec.tx_index = Some(0);
            rec.success = Some(true);
            self.state
                .block_transactions
                .entry(self.state.slot)
                .or_default()
                .push(hash);
        }

        SlotResult {
            slot: self.state.slot,
            leader: self.state.current_leader.clone(),
            kind: BlockKind::Validator,
            tx_count,
            gas_used: gas,
            fees_burned: fees as u64,
        }
    }

    pub(super) fn protocol_miss_block(&mut self) -> SlotResult {
        if self.state.local_validator_id.as_deref() != Some(self.state.current_leader.as_str()) {
            // Standard nodes cannot know whether a remote leader was truly absent; avoid provisional penalties.
            return SlotResult {
                slot: self.state.slot,
                leader: self.state.current_leader.clone(),
                kind: BlockKind::ProtocolMiss,
                tx_count: 0,
                gas_used: 0,
                fees_burned: 0,
            };
        }
        if let Some(v) = self
            .state
            .validators
            .iter_mut()
            .find(|v| v.id == self.state.current_leader)
        {
            v.miss_counter += 1;
            if v.miss_counter >= 10 {
                v.state = ValidatorState::PunishedCooldown;
                v.cooldown_until_epoch = Some(self.state.epoch_index + 1);
            }
        }
        SlotResult {
            slot: self.state.slot,
            leader: self.state.current_leader.clone(),
            kind: BlockKind::ProtocolMiss,
            tx_count: 0,
            gas_used: 0,
            fees_burned: 0,
        }
    }

    pub(super) fn protocol_collision_block(&mut self) -> SlotResult {
        SlotResult {
            slot: self.state.slot,
            leader: self.state.current_leader.clone(),
            kind: BlockKind::ProtocolCollision,
            tx_count: 0,
            gas_used: 0,
            fees_burned: 0,
        }
    }

    pub(super) fn protocol_no_tickets_block(&mut self) -> SlotResult {
        let mut tx_count = 0_u32;
        let mut gas_used = 0_u64;
        let mut fees_burned = 0_u64;

        if let Some(index) = self.select_pbm_tx_index()
            && let Some(tx) = self.state.pbm_pool.remove(index)
            && let Some((gas, fees)) = self.execute_pbm_tx(tx)
        {
            // PBM advances the chain without tickets but only includes one deterministic bootstrap tx per slot.
            tx_count = 1;
            gas_used = gas;
            fees_burned = fees;
            let fees = fees as u128;
            self.state.fees_burned_total = self.state.fees_burned_total.saturating_add(fees);
            self.state.burn_this_sub_epoch = self.state.burn_this_sub_epoch.saturating_add(fees);
            self.state.sub_epoch_burned_quarks =
                self.state.sub_epoch_burned_quarks.saturating_add(fees);
            self.state.epoch_burned_quarks = self.state.epoch_burned_quarks.saturating_add(fees);
        }

        self.deactivate_pbm_if_ready();

        SlotResult {
            slot: self.state.slot,
            leader: "protocol".to_string(),
            kind: BlockKind::ProtocolNoTickets,
            tx_count,
            gas_used,
            fees_burned,
        }
    }

    pub(super) fn select_pbm_tx_index(&self) -> Option<usize> {
        let mut candidates: Vec<(usize, u64, String)> = self
            .state
            .pbm_pool
            .iter()
            .enumerate()
            .filter(|(_, tx)| {
                Protocol::pbm_allowed_kind(tx.kind) && tx.valid_after_slot <= self.state.slot
            })
            .map(|(index, tx)| (index, tx.valid_after_slot, tx_id(tx)))
            .collect();
        candidates.sort_by(|a, b| (a.1, &a.2).cmp(&(b.1, &b.2)));
        candidates.first().map(|(index, _, _)| *index)
    }

    pub(super) fn execute_pbm_tx(&mut self, tx: Tx) -> Option<(u64, u64)> {
        let fee = tx.fee_quarks as u128;
        match tx.kind {
            "registerValidator" => {
                let (validator_pubkey, reward_address) = decode_register_validator_data(&tx.data)?;
                let validator_pubkey = self.normalize_validator_pubkey(&validator_pubkey)?;
                if self.state.validators.iter().any(|v| v.id == tx.to)
                    || self.validator_pubkey_registered(&validator_pubkey)
                    || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, fee)
                {
                    return None;
                }
                if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                    return None;
                }
                self.register_validator_record(tx.to, &tx.from, validator_pubkey, reward_address);
                Some((tx.gas, tx.fee_quarks))
            }
            "walletToVault" => {
                let required = tx.value.saturating_add(fee);
                if self.validator_owner_account(&tx.to).as_deref() != Some(tx.from.as_str())
                    || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, required)
                    || !self.state.validators.iter().any(|v| v.id == tx.to)
                {
                    return None;
                }
                if !self.debit_balance(&tx.from, TOKEN_ETX_ID, tx.value) {
                    return None;
                }
                if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                    self.credit_balance(&tx.from, TOKEN_ETX_ID, tx.value);
                    return None;
                }
                if let Some(v) = self.state.validators.iter_mut().find(|v| v.id == tx.to) {
                    v.vault_quarks = v.vault_quarks.saturating_add(tx.value);
                    self.refresh_validator_activation(&tx.to);
                    return Some((tx.gas, tx.fee_quarks));
                }
                self.credit_balance(&tx.from, TOKEN_ETX_ID, tx.value);
                None
            }
            "buyTicket" => {
                let count = u64::try_from(tx.value).ok().filter(|count| *count > 0)?;
                let cost = TICKET_COST_QUARKS.saturating_mul(tx.value);
                let required = cost.saturating_add(fee);
                if self.validator_owner_account(&tx.to).as_deref() != Some(tx.from.as_str())
                    || !self.can_pay_fee(&tx.from, TOKEN_ETX_ID, required)
                {
                    return None;
                }
                if !self.debit_balance(&tx.from, TOKEN_ETX_ID, cost) {
                    return None;
                }
                if !self.debit_balance(&tx.from, TOKEN_ETX_ID, fee) {
                    self.credit_balance(&tx.from, TOKEN_ETX_ID, cost);
                    return None;
                }
                self.burn_and_mint_tickets(&tx.to, count);
                self.refresh_validator_activation(&tx.to);
                Some((tx.gas, tx.fee_quarks))
            }
            _ => None,
        }
    }

    pub(super) fn deactivate_pbm_if_ready(&mut self) {
        if self.total_eligible_tickets() == 0 {
            return;
        }
        self.state.mode = Mode::Normal;
        while let Some(mut tx) = self.state.pbm_pool.pop_front() {
            tx.valid_after_slot = 0;
            self.state.mempool.push_back(tx);
        }
        self.state
            .events
            .push_front("PBM deactivated: eligible ticket available".to_string());
    }

    pub(super) fn run_boundaries(&mut self) {
        if self.state.slot > 0 && self.state.slot.is_multiple_of(SUB_EPOCH_SLOTS) {
            let produced = self
                .state
                .blocks_this_sub_epoch
                .iter()
                .filter(|p| p.is_some())
                .count() as u64;
            if produced > 0 {
                let k = self.state.burn_offset_k_permille as u128;
                let opb = k * self.state.burn_this_sub_epoch / 1000 / produced as u128;
                let proposers: Vec<String> = self
                    .state
                    .blocks_this_sub_epoch
                    .iter()
                    .flatten()
                    .cloned()
                    .collect();
                for pid in proposers {
                    if self.state.validators.iter().any(|v| v.id == pid) {
                        // Burn-offset is minted at sub-epoch close from fee burns only, not ticket burns.
                        self.lock_validator_reward(&pid, opb);
                        self.state.burn_offset_total += opb;
                        self.state.epoch_issued_quarks =
                            self.state.epoch_issued_quarks.saturating_add(opb);
                    }
                }
            }
            for v in &mut self.state.validators {
                v.blocks_this_sub_epoch = 0;
            }
            self.state.burn_this_sub_epoch = 0;
            self.state.sub_epoch_issued_quarks = 0;
            self.state.sub_epoch_burned_quarks = 0;
            self.state.blocks_this_sub_epoch.clear();
            self.state.sub_epoch_index += 1;
            self.state.events.push_front(format!(
                "sub-epoch transition {}",
                self.state.sub_epoch_index
            ));
        }
        if self.state.slot > 0
            && self
                .state
                .slot
                .is_multiple_of(SUB_EPOCH_SLOTS * EPOCH_SUB_EPOCHS)
        {
            let next_epoch = self.state.epoch_index + 1;
            if next_epoch.is_multiple_of(EPOCHS_PER_YEAR) {
                // Inflation decay updates the fixed block reward for the next annual period.
                self.state.annual_inflation_ppb =
                    (self.state.annual_inflation_ppb * 9 / 10).max(5_000_000);
                self.recompute_base_reward_per_block();
            }
            self.state.epoch_index = next_epoch;
            self.unlock_rewards_for_epoch(next_epoch);
            self.state.epoch_issued_quarks = 0;
            self.state.epoch_burned_quarks = 0;
            self.finalize_retire_for_epoch(self.state.epoch_index);
            self.rotate_epoch_seed();
            self.process_epoch_validator_transitions();
            self.state
                .events
                .push_front(format!("epoch transition {}", self.state.epoch_index));
        }
    }

    pub(super) fn record_hash(&mut self, r: &SlotResult) {
        self.state.prev_hash =
            hash_bytes(format!("{}-{}-{}", r.slot, r.leader, r.tx_count).as_bytes());
    }

    pub(super) fn record_slot(&mut self, result: SlotResult) {
        self.state.current_result = Some(result.clone());
        // Recent provisional miss/no-ticket entries can be replaced by late validator blocks from peers.
        let replaced = self
            .state
            .history
            .iter()
            .find(|h| h.slot == result.slot)
            .cloned();
        let replacing = replaced.is_some();
        self.state.history.retain(|h| h.slot != result.slot);
        if let Some(old) = &replaced {
            self.revert_replaced_result(old, &result);
        }
        self.update_liveness(&result);
        self.state.blocks_this_sub_epoch.push(match result.kind {
            BlockKind::Validator => Some(result.leader.clone()),
            _ => None,
        });
        self.record_block(&result);
        self.state.history.push_front(result);
        if self.state.history.len() > 50 {
            self.state.history.pop_back();
        }
        if replacing {
            self.rebuild_liveness_from_history();
        }
    }

    pub(super) fn merge_slot_result(&mut self, result: SlotResult) {
        // Peer history is correction-only after bootstrap: validator blocks can replace weaker local results.
        let existing = self
            .state
            .history
            .iter()
            .find(|h| h.slot == result.slot)
            .cloned();
        let should_apply = match existing.as_ref() {
            Some(old) if old.kind == BlockKind::Validator => false,
            Some(old)
                if result.kind == BlockKind::Validator && old.kind != BlockKind::Validator =>
            {
                true
            }
            None => true,
            _ => false,
        };
        if !should_apply {
            return;
        }

        self.state.history.retain(|h| h.slot != result.slot);
        if let Some(old) = &existing {
            self.revert_replaced_result(old, &result);
        }
        self.record_block(&result);
        self.state.history.push_front(result.clone());

        let mut entries: Vec<SlotResult> = self.state.history.iter().cloned().collect();
        entries.sort_by_key(|e| std::cmp::Reverse(e.slot));
        entries.truncate(50);
        self.state.history = std::collections::VecDeque::from(entries);
        self.rebuild_liveness_from_history();
        self.state.events.push_front(format!(
            "slot {} corrected from peer: {:?}",
            result.slot, result.kind
        ));
    }

    pub(super) fn revert_replaced_result(&mut self, old: &SlotResult, new: &SlotResult) {
        // Undo local provisional punishment if a valid validator block later replaces the miss.
        if old.kind != BlockKind::ProtocolMiss
            || new.kind != BlockKind::Validator
            || old.leader != new.leader
        {
            return;
        }
        let mut refresh_id = None;
        if let Some(v) = self
            .state
            .validators
            .iter_mut()
            .find(|v| v.id == old.leader)
        {
            if v.miss_counter > 0 {
                v.miss_counter -= 1;
            }
            if v.state == ValidatorState::PunishedCooldown && v.miss_counter < 10 {
                v.cooldown_until_epoch = None;
                v.state = ValidatorState::Inactive;
                refresh_id = Some(v.id.clone());
            }
        }
        if let Some(id) = refresh_id {
            self.refresh_validator_activation(&id);
        }
    }

    pub(super) fn record_block(&mut self, result: &SlotResult) {
        let number = result.slot;
        let hash = format!("0x{}", hex::encode(block_hash_bytes(number)));
        let parent_hash = if number == 0 {
            "0x0000000000000000000000000000000000000000000000000000000000000000".to_string()
        } else {
            format!("0x{}", hex::encode(block_hash_bytes(number - 1)))
        };
        let timestamp_ms = unix_ms_now() as u64;
        let tx_hashes = self
            .state
            .block_transactions
            .get(&number)
            .cloned()
            .unwrap_or_default();
        let rec = BlockRecord {
            number,
            hash: hash.clone(),
            parent_hash,
            timestamp_ms,
            gas_used: result.gas_used,
            tx_hashes,
        };
        self.state.block_hash_to_number.insert(hash, number);
        self.state.blocks.insert(number, rec);
    }

    pub(super) fn update_liveness(&mut self, result: &SlotResult) {
        let epoch = result.slot / (SUB_EPOCH_SLOTS * EPOCH_SUB_EPOCHS);
        if epoch != self.state.liveness_epoch {
            self.state.liveness_epoch = epoch;
            self.state.liveness_counted_slots.clear();
            self.state.liveness_total_slots = 0;
            self.state.liveness_validator_slots = 0;
        }
        if !self.state.liveness_counted_slots.insert(result.slot) {
            return;
        }
        self.state.liveness_total_slots += 1;
        if result.kind == BlockKind::Validator {
            self.state.liveness_validator_slots += 1;
        }
        self.state.epoch_total_slots = self.state.liveness_total_slots;
        self.state.epoch_validator_blocks = self.state.liveness_validator_slots;
    }

    pub(super) fn rebuild_liveness_from_history(&mut self) {
        self.state.liveness_counted_slots.clear();
        self.state.liveness_total_slots = 0;
        self.state.liveness_validator_slots = 0;

        let mut entries: Vec<SlotResult> = self.state.history.iter().cloned().collect();
        entries.sort_by_key(|e| e.slot);
        if let Some(last) = entries.last() {
            self.state.liveness_epoch = last.slot / (SUB_EPOCH_SLOTS * EPOCH_SUB_EPOCHS);
        }
        for e in &entries {
            let epoch = e.slot / (SUB_EPOCH_SLOTS * EPOCH_SUB_EPOCHS);
            if epoch != self.state.liveness_epoch {
                continue;
            }
            if self.state.liveness_counted_slots.insert(e.slot) {
                self.state.liveness_total_slots += 1;
                if e.kind == BlockKind::Validator {
                    self.state.liveness_validator_slots += 1;
                }
            }
        }
        self.state.epoch_total_slots = self.state.liveness_total_slots;
        self.state.epoch_validator_blocks = self.state.liveness_validator_slots;
    }

    pub(super) fn rotate_epoch_seed(&mut self) {
        let mut data = Vec::new();
        data.extend_from_slice(&self.state.epoch_seed);
        data.extend_from_slice(&self.state.epoch_index.to_be_bytes());
        self.state.epoch_seed = hash_bytes(&data);
    }

    pub(super) fn process_epoch_validator_transitions(&mut self) {
        let mut refresh_ids = Vec::new();
        let vault_minimums: HashMap<String, u128> = self
            .state
            .validators
            .iter()
            .map(|v| (v.id.clone(), self.validator_vault_minimum_quarks(&v.id)))
            .collect();
        for v in &mut self.state.validators {
            if v.state == ValidatorState::Jailed {
                continue;
            }
            if v.state == ValidatorState::PunishedCooldown
                && let Some(until) = v.cooldown_until_epoch
                && self.state.epoch_index >= until
            {
                v.cooldown_until_epoch = None;
                let vault_minimum = vault_minimums.get(&v.id).copied().unwrap_or(0);
                if v.vault_quarks >= vault_minimum {
                    v.state = ValidatorState::Inactive;
                    refresh_ids.push(v.id.clone());
                } else {
                    v.state = ValidatorState::PausedLowVault;
                }
            }
        }
        for id in refresh_ids {
            self.refresh_validator_activation(&id);
        }
    }

    pub(super) fn finalize_retire_for_epoch(&mut self, epoch: u64) {
        let Some(ticket_ids) = self.state.retire_finalize.remove(&epoch) else {
            return;
        };
        let mut owners = Vec::new();
        for tid in ticket_ids {
            if let Some(t) = self.state.tickets.iter_mut().find(|t| t.id == tid) {
                owners.push(t.owner.clone());
                t.dead = true;
                t.muted = false;
                t.retiring = false;
                t.bucket = 0;
            }
        }
        owners.sort_unstable();
        owners.dedup();
        for owner in owners {
            self.refresh_validator_activation(&owner);
        }
    }
}
